"""Crab vision helpers for the MATE ROV invasive species task."""

from triton_analysis.crab.counter import (
    CrabCountResult,
    CrabBenchmarkOutputs,
    CrabBoardOutlineResult,
    CrabCounterConfig,
    CrabCounterOutputs,
    CrabDetection,
    CrabPreprocessResult,
    analyze_crab_image,
    auto_preprocess_crab_target_image,
    benchmark_crab_image,
    detect_crab_board_homography,
    discover_crab_board_reference_paths,
    discover_counter_reference_atlas_paths,
    discover_counter_reference_paths,
    draw_crab_count_result,
    preprocess_crab_target_image,
    transform_crab_count_result,
    write_reference_atlas,
)
from triton_analysis.crab.synthetic import (
    CRAB_CLASS_NAMES,
    SyntheticDatasetConfig,
    SyntheticDatasetResult,
    discover_background_media,
    generate_synthetic_dataset,
)
from triton_analysis.crab.plane_dataset import (
    BoardPlaneAnnotation,
    PlaneProjectedDatasetConfig,
    discover_board_images,
    discover_default_crab_template_paths,
    generate_plane_projected_dataset,
    load_board_plane_annotations,
    save_board_plane_annotations,
)

__all__ = [
    "BoardPlaneAnnotation",
    "CRAB_CLASS_NAMES",
    "CrabBenchmarkOutputs",
    "CrabBoardOutlineResult",
    "CrabCountResult",
    "CrabCounterConfig",
    "CrabCounterOutputs",
    "CrabDetection",
    "CrabPreprocessResult",
    "PlaneProjectedDatasetConfig",
    "SyntheticDatasetConfig",
    "SyntheticDatasetResult",
    "analyze_crab_image",
    "auto_preprocess_crab_target_image",
    "benchmark_crab_image",
    "detect_crab_board_homography",
    "discover_crab_board_reference_paths",
    "discover_background_media",
    "discover_board_images",
    "discover_counter_reference_atlas_paths",
    "discover_counter_reference_paths",
    "discover_default_crab_template_paths",
    "draw_crab_count_result",
    "generate_plane_projected_dataset",
    "generate_synthetic_dataset",
    "load_board_plane_annotations",
    "preprocess_crab_target_image",
    "save_board_plane_annotations",
    "transform_crab_count_result",
    "write_reference_atlas",
]
